---
resources:
  - name: concourse-git
    type: git
    source:
      uri: https://github.com/ddunlop/concourse-test.git
      branch: master

jobs:
  - name: concourse-test
    plan:
      - get: concourse-git
      - task: git_metadata
        file: concourse-git/git_metadata.yml
      - task: rollbar
        file: concourse-git/rollbar.yml
        params:
          ENVIRONMENT: staging
          ROLLBAR_ACCESS_TOKEN: test_token
