---
resources:
  - name: concourse-test
    type: git
    source:
      uri: https://github.com/ddunlop/concourse-test.git
      branch: master

jobs:
  - name: concourse-test
    public: true
    plan:
      - get: concourse-test
      - task: tag
        # file: rollbar.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: onemedical/onelife-script

            inputs:
              - name: concourse-test
              run:
                path: concourse-test/deploy-scripts/rollbar.sh
                args:
                - git_metadata/TAG
                params:
                  ENVIRONMENT:
