---
resources:
  - name: concourse-test
    type: git
    source:
      uri: https://github.com/ddunlop/concourse-test.git
      branch: master

jobs:
  - name: concourse-test
    public: true
    plan:
      - get: concourse-test
      - task: git_metadata
        file: concourse-test/git_metadata.yml
      - task: rollbar
        file: concourse-test/rollbar.yml
        params:
          ENVIRONMENT: staging
          ROLLBAR_ACCESS_TOKEN: test_token
